sudo: false
dist: bionic
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO=1.10 DRF=3.7
  - DJANGO=1.10 DRF=3.8
  - DJANGO=1.11 DRF=3.7
  - DJANGO=1.11 DRF=3.8
  - DJANGO=1.11 DRF=3.9
  - DJANGO=1.11 DRF=3.10
  - DJANGO=2.0 DRF=3.8
  - DJANGO=2.0 DRF=3.9
  - DJANGO=2.0 DRF=3.10
  - DJANGO=2.1 DRF=3.9
  - DJANGO=2.1 DRF=3.10
  - DJANGO=2.2 DRF=3.10
install: pip install tox-travis
script: tox
