sudo: false
dist: bionic
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - TOXENV=django1.10-drf3.7
  - TOXENV=django1.10-drf3.8
  - TOXENV=django1.11-drf3.7
  - TOXENV=django1.11-drf3.8
  - TOXENV=django1.11-drf3.9
  - TOXENV=django1.11-drf3.10
  - TOXENV=django2.0-drf3.8
  - TOXENV=django2.0-drf3.9
  - TOXENV=django2.0-drf3.10
  - TOXENV=django2.1-drf3.9
  - TOXENV=django2.1-drf3.10
  - TOXENV=django2.2-drf3.10
install: pip install tox-travis
script: tox
