[tox]

# Django version vs Python version

#       3.7  3.8  3.9  3.10
# 2.0    x
# 2.1    x
# 2.2    x    x
# 3.0    x    x    x
# 3.1    x    x    x
# 3.2    x    x    x    x

# Django version vs Django REST Framework version

#       3.9  3.10 3.11 3.12 3.13
# 2.0    x    x    x
# 2.1    x    x    x
# 2.2    x    x    x    x    x
# 3.0              x    x    x
# 3.1                   x    x
# 3.2                        x

envlist =
    py{38,39}-django{2.2,3.0,3.1,3.2},
    py310-django3.2

[default]

[testenv]
basepython =
    py38: python3.8
    py39: python3.9
    py310: python3.10
deps =
    mock
    celery<5.3  # 5.2.7
    pytz
    python-dateutil
    django2.2: django<2.3
    django3.0: django<3.1
    django3.1: django<3.2
    django3.2: django<3.3
    djangorestframework<3.14
    file://{toxinidir}/sample_project/
setenv =
    PYTHONPATH={toxinidir}
    DJANGO_SETTINGS_MODULE=sample_project.settings
commands = {envpython} {envbindir}/django-admin.py test turngeneration
