# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-12-10 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.PositiveSmallIntegerField(blank=True, choices=[(0, b'Yearly'), (1, b'Monthly'), (2, b'Weekly'), (3, b'Daily'), (4, b'Hourly'), (5, b'Minutely')], default=3)),
                ('dtstart', models.DateTimeField(blank=True, null=True)),
                ('interval', models.PositiveIntegerField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('bysetpos', models.CharField(blank=True, max_length=64, validators=[validate_comma_separated_integer_list])),
                ('bymonth', models.CharField(blank=True, max_length=64, validators=[validate_comma_separated_integer_list])),
                ('bymonthday', models.CharField(blank=True, max_length=64, validators=[validate_comma_separated_integer_list])),
                ('byyearday', models.CharField(blank=True, max_length=64, validators=[validate_comma_separated_integer_list])),
                ('byweekno', models.CharField(blank=True, max_length=64, validators=[validate_comma_separated_integer_list])),
                ('byweekday', models.CharField(blank=True, max_length=64, validators=[validate_comma_separated_integer_list])),
                ('byhour', models.CharField(blank=True, max_length=64, validators=[validate_comma_separated_integer_list])),
                ('byminute', models.CharField(blank=True, max_length=64, validators=[validate_comma_separated_integer_list])),
            ],
        ),
        migrations.CreateModel(
            name='GenerationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('generating', models.BooleanField(default=False)),
                ('generation_time', models.DateTimeField(null=True)),
                ('task_id', models.TextField()),
                ('force_generate', models.BooleanField(default=True)),
                ('autogenerate', models.BooleanField(default=True)),
                ('allow_pauses', models.BooleanField(default=True)),
                ('minimum_between_generations', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Pause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='turngeneration.Generator')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ready',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readies', to='turngeneration.Generator')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='generationtime',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='turngeneration.Generator'),
        ),
        migrations.AddField(
            model_name='generationrule',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='turngeneration.Generator'),
        ),
        migrations.AlterUniqueTogether(
            name='ready',
            unique_together=set([('content_type', 'object_id', 'generator')]),
        ),
        migrations.AlterUniqueTogether(
            name='pause',
            unique_together=set([('content_type', 'object_id', 'generator')]),
        ),
        migrations.AlterUniqueTogether(
            name='generator',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
