# Generated by Django 2.2.28 on 2025-12-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turngeneration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='allow_pauses',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='autogenerate',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='force_generate',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='generator',
            name='generating',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterUniqueTogether(
            name='generator',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pause',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ready',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='generator',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='generator_unique_generic_fk'),
        ),
        migrations.AddConstraint(
            model_name='pause',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'generator'), name='pause_per_generator_and_agent'),
        ),
        migrations.AddConstraint(
            model_name='ready',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'generator'), name='ready_per_generator_and_agent'),
        ),
    ]
